server:
  port: 8080

spring:
  application:
    name: CUSTOMER
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:dcbapp
    driverClassName: org.h2.Driver
    username: sa
    password: password
    ddl-auto: create-drop
    pool-size: 30
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8180/eureka/
  instance:
    hostname: localhost